bump-sh/github-action

package-lock.json
package.json
src/common.ts
src/diff.ts
src/github.ts
src/main.ts
tests/diff.test.ts
tests/main.test.ts

_Needs v2.1.0 of `bump-cli` npm package. [Released ✓](https://www.npmjs.com/package/bump-cli/v/2.1.0)_
This PR adds the usage of the new `diff` command of the CLI to be able to send Documentation changes to github PR comments.
The PR is separate in three main commits:
- feat: send diff results to github PR comment
- feat: add a new 'diff' command to be able to detect doc changes
- test: simplified test cases with already mocked imports
Here's the first test: https://github.com/bump-sh/bump/pull/758#issuecomment-871302392

feat: send diff results to github PR comment

---

src/common.ts
src/diff.ts
tests/common.test.ts
tests/diff.test.ts

Until now we considered a Diff comment to be digested by its summary
only, however this is confusing for users because they don't see later
updates when there's no structural changes between a first diff
comment and a later commit.
With this PR we include the diff public url to be part of the
digest to make sure we update the bot GH comment when the diff
changes.
Thank you @gmourier for mentioning this issue during your tests in
https://github.com/meilisearch/specifications/pull/58! 😊

diff: update GH comment when diff public URL changes

---

package-lock.json
package.json
src/diff.ts
tests/diff.test.ts

Since we now send a [more precise information](https://developers.bump.sh/changes/a71bf771-693f-49b1-95b3-756b67e9d7bf#get-versions-parameter-200-diff_breaking) about the diff in the API,
we can change the title of the Github comment to attract the users
attention on the fact the changes are *breaking*.
~_Waiting for https://github.com/bump-sh/cli/pull/155 release_~
Closes #133

diff: update title of GH comment on breaking changes

---

package-lock.json
package.json
src/github.ts
src/main.ts
tests/main.test.ts

~_Requirements: Bump CLI needs to be updated to support two files
input. cf https://github.com/bump-sh/cli/pull/141_~ [v2.2.2](https://github.com/bump-sh/cli/releases/tag/v2.2.2) of the CLI is released :tada:
The current 'diff' command of this action will only be able to produce
a diff with the currently deployed API definition file on
bump.sh. This is nice when you merge API changes in a single branch
one after another. However in the context of multiple parallel
changes, and with the notion of “staging” API definition file (file not yet
deployed but which is considered as the most up-to-date base), this
diff process doesn't make much sense. Why? because it will include all
changes made to the “staging” version in your own PR change.
Thus, this PR reads the PR base ref to be able to …

diff: use pull request base ref to perform Bump Diff

---

package-lock.json
package.json

This is a necessary upgrade for the Pull request diff to work
correctly (comparing base branch with head branch).
Should have been part of #139.

upgrade: bump-cli needs to be at least 2.2.3 for two files diff

---

package-lock.json
package.json
src/main.ts

There's a small breaking changes on catched errors, they are now typed
as `unknown` (instead of `Error`).
Replace / closes #123

Upgrade typescript from 4.3 to 4.4

---

src/github.ts
tests/fixtures/github-context.json
tests/github.test.ts
tsconfig.json

API contract files can be split out in multiple files to favor
reusability and readability. This is done thanks to the `$ref`
[references objects](https://spec.openapis.org/oas/v3.1.0#reference-object).
For our `diff` command we need to restore the previous version of the
contract file to be able to compare previous with current HEAD. The
current implementation would only restore the given root file.
With this PR we restore the entire repository in its merge-base
version. This will avoid any errors while needing to compare two API
contract files which are written with external reference objects.
Fixes #179

fix: make sure to restore all repository for diff command

---

package-lock.json
package.json
src/common.ts
src/diff.ts
src/github.ts
src/main.ts
tests/diff.test.ts
tests/github.test.ts
tests/main.test.ts

With bump-sh/cli#192 we are migrating to Diff core logic into a
dedicated class so it can be re-used here without the need to
programmatically call the Oclif command (which is [not recommended](https://oclif.io/docs/running_programmatically))
Here is an example run: https://github.com/paulRbr/bump/pull/8#issuecomment-1011943935

core: use newly exported Diff lib instead of Diff cmd from CLI

---

action.yml
package-lock.json
package.json
src/diff.ts
src/main.ts
tests/diff.test.ts
tests/main.test.ts

This change is necessary to support “public diffs” (diff with no
authentication). It adapts the interface used from the `bump-cli`
package to use the new `DiffResponse` model which is the new output of
the diff library.
_Needs: new release of the CLI to support public diff (https://github.com/bump-sh/cli/pull/221)_

diff: use latest model exposed by new bump-cli version

---

package-lock.json
package.json

What a day! (2022-02-03) to support AsyncAPI 2.3 in the Bump GitHub
Action. 😁
Check out their blog post announcement: https://www.asyncapi.com/blog/release-notes-2.3.0

packages: bump the bump-cli package to support AsyncAPI 2.3

---

README.md
jest.config.js
package-lock.json
package.json
src/main.ts
tests/helpers.d.ts
tests/main.test.ts
tests/setup-test-env.ts
tsconfig.test.json

Following the latest release of the CLI
https://github.com/bump-sh/cli/releases/tag/v2.4.0 this commit adapts
the GH action to accept a new input parameter `branch` to be able to
deploy versions to dedicated branches.

core: update 'bump-cli' dependency to introduce Branch input

---

action.yml

Since we introduced branch feature in #252 we forgot to add the input
name `branch` in the action.yml metadata file (read by GH action).
It seems we also never added the `hub` action input in that file so
this commit fixes that too.
Closes #275

fix: remove useless warnings on action runs for missing inputs

---

src/common.ts
src/diff.ts
src/github.ts
src/main.ts
tests/common.test.ts
tests/diff.test.ts
tests/github.test.ts
tests/main.test.ts

Before this commit all comments published to GH on the diff feature
would be independent from the potential documentation/hub id (or slug)
given to the GH action inputs.
However, some of our users may want to use the GH action on multiple
different specification files (attached to different docs).
Thus with this commit we add the “context” of the documentation in the
comment signature. In this way we can remove only previous comments
for the given documentation (and avoid deleting any of the other Bump
comments)

fix(diff): add “doc” related context in GH diff comments

---

src/diff.ts
tests/diff.test.ts

Without this fix the diff action would fail so we need to check the
presence of the `diff.public_url` value before using it.

fix: we have made the diff public_url optional backend side

---

README.md

Since February 2nd, 2023, the default `GITHUB_TOKEN` permissions are set to read-only for every new repository.
Permissions have to be explicitly defined in workflow examples.
source: https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
cf https://github.com/bump-sh/bump/issues/3037

Define permissions

---

README.md
action.yml
package-lock.json
package.json
src/main.ts
tests/main.test.ts

Similarly to the recent changes on the
CLI (https://github.com/bump-sh/cli/pull/445) we introduce a new GH
action input parameter `fail_on_breaking` to allow diff command to
fail the build when there's a breaking change detected in the API diff.
---
Bonus of this PR we upgrade the CLI to the latest 2.6.0

diff: add a `fail_on_breaking` input parameter

---

package-lock.json
package.json

Make sure to use the latest version of our CLI. This will fix a bug with sub-dependencies on the Github Action where a user couldn't deploy a 2.6.0 AsyncAPI definition file.

deps: Upgrade bump-cli to latest version

---

README.md

Two commits with this PR:
- 1st, let's favor our official name Bump.sh
- 2nd, a suggestion to redirect a link to dashboard (instead of root marketing page).

Tiny copywriting in Readme

---

package-lock.json
package.json

Tiny follow-up to #454, where the package-lock file was not updated with the minimal version of the `bump-cli` package to use.
This PR also removes an unecessary explicit dependency on `@oclif/core` (which is not used by the github-action code itself).

deps: remove useless explicit dependency

---

action.yml

This commit modifes the Action metadata to have a more meaningful name
on the GitHub marketplace (currently when searching for “API
documentation” on the marketplace doesn't show the Bump.sh action..)
Following up with https://github.com/bump-sh/docs/pull/235

docs: rename the GH action on marketplace

---

src/common.ts
src/diff.ts
src/main.ts
tests/diff.test.ts
tests/main.test.ts

This commit makes sure to have a different behavior during a diff
between a No Change at all result, vs a No Content Change result.
Before this commit we would only display a “No diff found” message in
the GH action logs.
With this new commit, if there's a content change detected we now
publish a comment containing a link to be able to preview the change.

diff: make sure to differentiate No Change vs Content change only

---

README.md

The file 'icon-default-large.png' has been removed from the Bump code base, duplication of 'icon-default-maskable-large.png'
The new maskable file is a circle

Rebrand: Update Readme logo

---

README.md
action.yml
src/main.ts
tests/main.test.ts

Adds support for an `overlay` input which allows an action user to provide one or more [OAI Overlays](https://github.com/OAI/Overlay-Specification).
Multiple supported by passing CSV as GitHub Actions do not yet support arrays.
Only one overlay will work until https://github.com/bump-sh/cli/pull/619 is merged.

feat: added overlay(s) support to deploy command

---

package-lock.json
package.json
src/main.ts
tests/main.test.ts

This commit adapts the `overlay` input parsing, to be able to send a
list of overlay files to the diff command if present.

overlays: send input overlays to the diff core lib

---

README.md
action.yml
src/main.ts
tests/main.test.ts

This change adds a new input `filename_pattern:` to be able to
customize the filename pattern to deploy a set of files in a directory
to a hub.

deploy: allow 'filename_pattern' input
